name: very_easy_localization
description: "Very Easy Localization: Very Easily Extract Strings From your Flutter App & create localization in 100+ languages using google translate with google translate."
version: 1.0.0
homepage: https://github.com/YashMakan/very_easy_localization

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args:
  path:
  translator: 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
